# Generated by Django 2.2.5 on 2021-01-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('sex', models.CharField(max_length=255, verbose_name='')),
                ('age', models.IntegerField(blank=True, verbose_name='')),
            ],
        ),
    ]
